name: GitHub Fetcher

on:
  push:
    branches:
      - main

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run fetcher script
        run: node scripts/github-fetcher.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
          APPWRITE_PROJECT: ${{ secrets.APPWRITE_PROJECT }}
          APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
